# This workflow runs a web scraper
# that indexes the prototype documentation site for Hazelcast Turbine
# and uploads that index to Algolia at the end of every day.

name: Index Turbine

on:
  schedule:
    - cron: "0 0 * * 1-5"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      APPLICATION_ID: ${{ secrets.ALGOLIA_APP_ID }}
      API_KEY: ${{ secrets.ALGOLIA_API_KEY }}

    steps:
    - uses: actions/checkout@v2
    - run: |
        docker run -e APPLICATION_ID=$APPLICATION_ID -e API_KEY=$API_KEY -e "CONFIG=$(cat search-config-turbine.json | jq -r tostring)" algolia/docsearch-scraper
